name: "test-c-preprocessor"

# Run this action on every push to master branch 
on:
  workflow_dispatch: # To manually run the job
  push:
    branches:
      - main
    paths:
      - components/hello-world/**
  # pull_request:
  #   branches:    
  #     - main

jobs:  
  linux:
    name: "Linux Varient"
    runs-on: ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v2.1.1

      - name: 🟢 node
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: '12.18.2'
          scope: '@naveed235812'
          registry-url: https://registry.npmjs.org

      - name: Install C-Preprocessor
        run: npm install -g c-preprocessor

      - name: Prepare and Execute C-Preprocessor
        run: |
          python prepareVariantConfig.py
        working-directory: ./components/hello-world
        env:
          VARIANT_TYPE: LINUX

      # - name: Execute C-Preprocessor
      #   run: |
      #     npm install c-preprocessor -g
      #     echo example of c-preprocessor
      #     c-preprocessor ./src/Main.ts ./src/Main.ts
      #   working-directory: ./components/hello-world

      - name: npm install
        run: npm install
        working-directory: ./components/hello-world

      - name: npm build
        run: npm run build
        working-directory: ./components/hello-world

      - name: npm test
        run: npm run test
        working-directory: ./components/hello-world

      - name: Execute Linux Variant
        run: node ./lib/index.js
        working-directory: ./components/hello-world
